include(FetchContent)
# Exact upstream commits, never floating branches. Qt is supplied by the SDK.
set(BUILD_SHARED_LIBS ON CACHE BOOL "Shared third party libraries")
set(BUILD_TESTING OFF)
set(WITH_EXAMPLES OFF CACHE BOOL "" FORCE)
set(WITH_SERVER OFF CACHE BOOL "" FORCE)
set(WITH_GSSAPI OFF CACHE BOOL "" FORCE)
set(WITH_ZLIB ON CACHE BOOL "" FORCE)
FetchContent_Declare(libssh GIT_REPOSITORY https://github.com/libssh/libssh-mirror.git GIT_TAG a09fdd00416e53b6ed436df6ff14339a4f884601)
set(BUILD_WITH_QT6 ON CACHE BOOL "" FORCE)
set(BUILD_TEST_APPLICATION OFF CACHE BOOL "" FORCE)
set(BUILD_TRANSLATIONS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(qtkeychain GIT_REPOSITORY https://github.com/frankosterfeld/qtkeychain.git GIT_TAG ad7344c45a86a4f66cbafc4b081b5f7b876cb0b7)
FetchContent_MakeAvailable(libssh qtkeychain)
FetchContent_Declare(libvterm GIT_REPOSITORY https://github.com/neovim/libvterm.git GIT_TAG 9d6d2112335080312ef8c36667fa717ded4f7daf)
FetchContent_MakeAvailable(libvterm)
file(GLOB vterm_sources CONFIGURE_DEPENDS "${libvterm_SOURCE_DIR}/src/*.c")
find_package(Python3 REQUIRED COMPONENTS Interpreter)
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_LIST_DIR}/generate_encodings.py"
  "${libvterm_SOURCE_DIR}/src/encoding" "${CMAKE_CURRENT_BINARY_DIR}/vterm-generated/encoding"
  COMMAND_ERROR_IS_FATAL ANY)
add_library(vterm STATIC ${vterm_sources})
set_target_properties(vterm PROPERTIES AUTOMOC OFF C_STANDARD 11)
target_include_directories(vterm PUBLIC "${libvterm_SOURCE_DIR}/include" PRIVATE "${libvterm_SOURCE_DIR}/src" "${CMAKE_CURRENT_BINARY_DIR}/vterm-generated")
set(BUILD_TESTING "${wiseshell_tests_enabled}")
